export const ADD_START_POINT = 'ADD_WAY_POINT';
export const SET_START_POINT = 'SET_START_POINT';
export const SET_CURRENT_USER_LOCATION = 'SET_CURRENT_USER_LOCATION';
export const ADD_WAY_POINT = 'ADD_WAY_POINT';
export const REMOVE_WAY_POINT = 'REMOVE_WAY_POINT';
export const FETCH_CURRENT_USER_LOCATION = 'FETCH_CURRENT_USER_LOCATION';
